import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { parseHTML } from 'linkedom'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

function sourceBody(path: string): string {
  const content = source(path)
  const header = content.match(/^\/\*\*[\s\S]*?\*\/\s*/u)?.[0]
  return header?.includes('@file ' + path) ? content.slice(header.length) : content
}

function sectionAt(content: string, sectionStart: number): string {
  const sectionTags = /<\/?section\b[^>]*>/gu
  sectionTags.lastIndex = sectionStart
  let depth = 0
  let match: RegExpExecArray | null
  while ((match = sectionTags.exec(content))) {
    depth += match[0].startsWith('</') ? -1 : 1
    if (depth === 0) return content.slice(sectionStart, sectionTags.lastIndex)
  }
  throw new Error(`Missing closing section at offset ${sectionStart}`)
}

function activeSectionSource(content: string, id: string): string {
  const openingSections = /<section\b[^>]*>/gu
  const sections: string[] = []
  let match: RegExpExecArray | null
  while ((match = openingSections.exec(content))) {
    if (match[0].includes(`props.activeSection === '${id}'`)) {
      sections.push(sectionAt(content, match.index))
    }
  }
  if (!sections.length) throw new Error(`Missing active section ${id}`)
  return sections.join('\n')
}

function settingsGroupTitles(content: string): string[] {
  return [...content.matchAll(/<SettingsGroup\b[^>]*\btitle="([^"]+)"/gu)]
    .map((match) => match[1])
}

function minimalPopupSpacing(viewportWidth: number, skin: string, dark: boolean, footerLast: boolean) {
  const { document } = parseHTML(`<html data-interface-skin="${skin}" class="${dark ? 'dark' : ''}">
    <head><style>${source('src/ui/styles/interface-skins/minimal.css')}</style></head>
    <body><main class="popup-shell"><div class="popup-content">
      <footer data-popup-module-last="${footerLast}"></footer>
    </div></main></body></html>`)
  const rules = document.querySelector('style')!.sheet!.cssRules

  // 解析真实 CSS 的像素间距与媒体覆盖，不模拟浏览器布局；渲染后的边界另由生产 UI 套件验证。
  function spacingFor(selector: string) {
    const element = document.querySelector(selector)!
    const spacing = { 'padding-left': 0, 'padding-right': 0, 'margin-left': 0, 'margin-right': 0 }
    function applyRules(cssRules: CSSRuleList) {
      for (const rule of Array.from(cssRules)) {
        if (rule.type === 4) {
          const media = rule as CSSMediaRule
          const maxWidth = media.conditionText.match(/^\(max-width:\s*(\d+)px\)$/u)
          if (!maxWidth) throw new Error(`Unsupported spacing media query: ${media.conditionText}`)
          if (viewportWidth <= Number(maxWidth[1])) applyRules(media.cssRules)
          continue
        }
        if (rule.type !== 1) continue
        const styleRule = rule as CSSStyleRule
        if (!element.matches(styleRule.selectorText)) continue
        for (let index = 0; index < styleRule.style.length; index += 1) {
          const property = styleRule.style[index]
          if (!(property in spacing) && property !== 'padding' && property !== 'margin') continue
          const values = styleRule.style.getPropertyValue(property).trim().split(/\s+/u).map(value => {
            if (!/^(?:-?\d+(?:\.\d+)?px|0)$/u.test(value)) throw new Error(`Unsupported spacing: ${value}`)
            return Number.parseFloat(value)
          })
          if (property === 'padding' || property === 'margin') {
            spacing[`${property}-left`] = values[3] ?? values[1] ?? values[0]
            spacing[`${property}-right`] = values[1] ?? values[0]
          } else {
            spacing[property as keyof typeof spacing] = values[0]
          }
        }
      }
    }
    applyRules(rules)
    return spacing
  }
  return { shell: spacingFor('.popup-shell'), footer: spacingFor('footer') }
}

describe('options UI composition architecture', () => {
  it('keeps persistent all-node recognition in advanced settings using the shared config and localized switch', () => {
    const sections = source('src/features/settings/ui/SettingsSections.vue')
    const advanced = activeSectionSource(sections, 'settings-advanced')
    expect(advanced).toContain('<SettingsGroup :title="t(\'settings.pageRecognition.title\')">')
    expect(advanced).toContain(':label="t(\'settings.pageRecognition.allNodes\')"')
    expect(advanced).toContain(':description="t(\'settings.pageRecognition.description\')"')
    expect(advanced).toContain('v-model="config.translationScope" active-value="all" inactive-value="content"')
    expect(advanced).toContain(':aria-label="t(\'settings.pageRecognition.allNodes\')"')
    expect(sections.match(/v-model="config\.translationScope"/gu)).toHaveLength(1)
    expect(source('src/app/popup/PopupApp.vue')).not.toContain('translationScope')
  })

  it.each([380, 400, 420, 421, 900])('keeps the minimal last footer inside its shell at a %ipx viewport', viewportWidth => {
    for (const dark of [false, true]) {
      const { shell, footer } = minimalPopupSpacing(viewportWidth, 'minimal', dark, true)
      const shellWidth = 380
      const left = shell['padding-left'] + footer['margin-left']
      const right = shellWidth - shell['padding-right'] - footer['margin-right']

      expect(left).toBe(0)
      expect(right).toBe(shellWidth)
      expect(shell['padding-left']).toBe(viewportWidth <= 420 ? 12 : 16)
      expect(shell['padding-right']).toBe(viewportWidth <= 420 ? 12 : 16)
    }
  })

  it.each([400, 900])('preserves inset footers and does not apply minimal spacing to the default skin at %ipx', viewportWidth => {
    const { shell, footer } = minimalPopupSpacing(viewportWidth, 'minimal', false, false)
    expect(footer['margin-left']).toBe(0)
    expect(footer['margin-right']).toBe(0)
    expect(shell['padding-left']).toBe(viewportWidth <= 420 ? 12 : 16)
    for (const dark of [false, true]) {
      const defaultSpacing = minimalPopupSpacing(viewportWidth, 'default', dark, true)
      expect(Object.values(defaultSpacing.shell)).toEqual([0, 0, 0, 0])
      expect(Object.values(defaultSpacing.footer)).toEqual([0, 0, 0, 0])
    }
  })

  it('keeps cache management inside advanced settings without another navigation or popup surface', () => {
    const sections = source('src/features/settings/ui/SettingsSections.vue')
    const cache = source('src/features/settings/ui/TranslationCacheSettings.vue')
    const navigation = source('src/features/settings/model/navigation.ts')
    const popup = source('src/app/popup/PopupApp.vue')

    expect(activeSectionSource(sections, 'settings-advanced')).toContain('<TranslationCacheSettings')
    expect(sections).toContain('<TranslationCacheSettings :config="config" />')
    expect(sections).toContain("v-if=\"hasVisitedSection('settings-advanced')\"")
    expect(navigation).toContain('缓存容量、存储大小、缓存条数、缓存上限、缓存阈值、清空缓存、清除缓存、LRU')
    expect(navigation).not.toContain("id: 'settings-cache'")
    expect(popup).not.toContain('TranslationCacheSettings')
    expect(cache).toContain('data-cache-bytes')
    expect(cache).toContain('data-cache-entries')
    expect(cache).toContain('<details class="translation-cache-limits" data-cache-limits>')
    expect(cache).toContain('aria-live="polite"')
    expect(cache).toContain('role="alert"')
    expect(cache).toContain('@submit.prevent="saveLimits"')
    expect(cache).toContain('requestConfigPatch(patch, browser.runtime.sendMessage.bind(browser.runtime))')
    expect(cache).toContain('getTranslationCacheStats()')
    expect(cache).toContain('clearManagedTranslationCache()')
    expect(cache).not.toContain('indexedDB')
    expect(cache).not.toContain('v-model="props.config.')
    expect(cache).not.toContain(':disabled="!props.config.useCache"')
    expect(cache).toContain("onUnmounted(() => { disposed = true; });")
    expect(cache).toContain('@media (max-width: 480px)')
    const advanced = activeSectionSource(sections, 'settings-advanced')
    expect(advanced).toContain('data-testid="api-key-recovery-setting"')
    expect(advanced).toContain("t('settings.requestLimits.apiKeyRecovery')")
    expect(advanced).toContain('@change="handleApiKeyRecoveryChange"')
  })

  it('keeps the WXT options entrypoint as a thin app composition shell', () => {
    const entrypoint = sourceBody('entrypoints/options/main.ts')
    expect(entrypoint).toBe("import { mountOptionsApp } from '@/src/app/options'\n\nmountOptionsApp('#app')\n")
  })

  it('defers options sections without dropping visited editing state and waits for hydrated UI resources', () => {
    const optionsApp = source('src/app/options/OptionsApp.vue')
    const optionsEntry = source('src/app/options/index.ts')
    const sections = source('src/features/settings/ui/SettingsSections.vue')

    expect(optionsApp).toContain('<KeepAlive>')
    expect(optionsApp).toContain('v-if="activeSection === \'settings-about\'"')
    expect(optionsApp).toContain('defineAsyncComponent(() => import(\'@/src/features/settings/ui/SettingsSections.vue\'))')
    expect(optionsEntry).toContain('await configReady')
    expect(optionsEntry).toContain('await ensureUiLanguageBundle(config.uiLanguage)')
    expect(optionsEntry).not.toContain('element-plus/dist/index.css')
    expect(sections).toContain('const visitedSections = ref(new Set<string>())')
    expect(sections).toContain('const hasVisitedSection = (section: string): boolean => visitedSections.value.has(section)')
    expect(sections).toContain("watch(() => props.activeSection, (section) => {")
    expect(sections).toContain('const scrollWhenMounted = () => {')
    expect(sections).toContain('if (attempts < 20) window.requestAnimationFrame(scrollWhenMounted)')
    for (const component of [
      'ServiceCatalog', 'ServiceConfiguration', 'InterfaceSettings',
      'ModelUsageDashboard', 'TranslationStatsDashboard', 'ConfigManagement', 'TranslationCenter',
    ]) {
      expect(sections).toContain(`const ${component} = defineAsyncComponent(`)
    }
  })

  it('keeps popup and options Element Plus styles component-scoped at the entrypoint boundary', () => {
    const popupEntry = source('src/app/popup/index.ts')
    const optionsEntry = source('src/app/options/index.ts')
    const requiredOptionsStyles = [
      'base', 'button', 'collapse', 'col', 'dialog', 'divider', 'empty', 'icon', 'input',
      'input-number', 'link', 'option', 'option-group', 'popover', 'row', 'select', 'switch',
      'text', 'tooltip', 'message', 'message-box', 'color-picker',
    ]

    expect(popupEntry).not.toContain('element-plus/dist/index.css')
    expect(optionsEntry).not.toContain('element-plus/dist/index.css')
    for (const component of requiredOptionsStyles) {
      expect(optionsEntry).toContain(`element-plus/es/components/${component}/style/css`)
    }
    for (const component of ['base']) {
      expect(popupEntry).toContain(`element-plus/es/components/${component}/style/css`)
    }
    expect(source('src/app/popup/PopupDrawer.ts')).toContain('element-plus/es/components/drawer/style/css')
    expect(popupEntry).not.toContain('ElInputNumber')
  })

  it('keeps the WXT popup entrypoint as a thin app composition shell', () => {
    const entrypoint = sourceBody('entrypoints/popup/main.ts')
    expect(entrypoint).toBe("import {mountPopupApp} from '@/src/app/popup';\n\nmountPopupApp('#app');\n")
  })

  it('mounts translation statistics lazily and keeps its copy in message keys', () => {
    const settingsSections = source('src/features/settings/ui/SettingsSections.vue')
    const statsPublic = source('src/features/translation-stats/public.ts')
    const dashboard = source('src/features/translation-stats/ui/TranslationStatsDashboard.vue')
    const dashboardBody = dashboard.replace(/^<!--[\s\S]*?-->\s*/u, '')

    expect(settingsSections).toContain("const TranslationStatsDashboard = defineAsyncComponent(() => import('@/src/features/translation-stats/public').then(module => module.TranslationStatsDashboard))")
    expect(settingsSections).toContain("v-if=\"hasVisitedSection('settings-translation-stats')\"")
    expect(settingsSections).toContain(":active=\"props.activeSection === 'settings-translation-stats'\"")
    expect(statsPublic).toContain("from './ui/TranslationStatsDashboard.vue'")
    expect(dashboard).toContain('id="settings-translation-stats"')
    expect(dashboard).toContain("type: 'translationStats'")
    for (const action of ['query', 'list', 'reset']) expect(dashboard).toContain(`action: '${action}'`)
    expect(dashboard).toContain('<style scoped src="./translation-stats-dashboard.css"></style>')
    // 面板只经后台消息读取数值快照；界面文案全部走 message key，避免遗漏其他界面语言。
    expect(dashboardBody).not.toMatch(/from 'dexie'|platform\/storage|indexedDB/u)
    const template = dashboardBody.match(/^<template>([\s\S]*)<\/template>/u)?.[1] ?? ''
    const script = dashboardBody.match(/<script setup lang="ts">([\s\S]*)<\/script>/u)?.[1] ?? ''
    expect(template).toContain('stats-summary')
    expect(template).not.toMatch(/[\u3400-\u9fff]/u)
    expect(script).not.toMatch(/['"`][^'"`\n]*[\u3400-\u9fff][^'"`\n]*['"`]/u)
  })

  it('owns settings, feature UI and shared components in their target layers', () => {
    const optionsApp = source('src/app/options/OptionsApp.vue')
    const settingsSections = source('src/features/settings/ui/SettingsSections.vue')
    const interfaceSettings = source('src/features/settings/ui/InterfaceSettings.vue')
    const interfaceSkinPreview = source('src/features/settings/ui/components/InterfaceSkinPreview.vue')
    const popupLayoutPreview = source('src/features/settings/ui/components/PopupLayoutPreview.vue')
    const popupLayoutPreviewItem = source('src/features/settings/ui/components/PopupLayoutPreviewItem.vue')
    const settingsItem = source('src/features/settings/ui/components/SettingsItem.vue')
    const popupLayoutEditor = source('src/features/settings/ui/PopupLayoutEditor.vue')
    const popupLayoutReorder = source('src/features/settings/ui/usePopupLayoutReorder.ts')
    const popupSiteRule = source('src/app/popup/PopupSiteRule.vue')
    const popupEntry = source('src/app/popup/index.ts')
    const optionsEntry = source('src/app/options/index.ts')
    const skinStyles = source('src/ui/styles/interface-skins.css')
    const minimalSkinStyles = source('src/ui/styles/interface-skins/minimal.css')
    const paletteSkinStyles = source('src/ui/styles/interface-skins/palette.css')
    const interfaceAppearance = source('src/ui/interfaceAppearance.ts')
    const popupHtml = source('entrypoints/popup/index.html')
    const configManagement = source('src/features/settings/ui/ConfigManagement.vue')
    const localDataManagement = source('src/features/settings/ui/LocalDataManagement.vue')
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const popup = source('src/app/popup/PopupApp.vue')
    const popupStyles = source('src/app/popup/popup.css')
    const modelUsageDashboard = source('src/features/model-usage/ui/ModelUsageDashboard.vue')
    const modelUsagePublic = source('src/features/model-usage/public.ts')
    const quickTranslationProfiles = source('src/features/settings/ui/QuickTranslationProfiles.vue')
    const translationShortcutSettings = source('src/features/settings/ui/useTranslationShortcutSettings.ts')
    const customHotkeyInput = source('src/ui/components/CustomHotkeyInput.vue')
    const inputTranslationSettings = source('src/features/settings/ui/InputTranslationSettings.vue')
    const inputTranslationMessages = source('src/core/i18n/messages/zh-CN.ts')

    expect(optionsApp).toContain("@/src/features/settings/ui/SettingsSections.vue")
    expect(optionsApp).toContain("window.addEventListener('hashchange', syncSectionFromHash)")
    expect(optionsApp).toContain("window.removeEventListener('hashchange', syncSectionFromHash)")
    expect(settingsSections).not.toContain('@/entrypoints/')
    expect(settingsSections).toContain('<style scoped src="./settings-sections.css"></style>')
    expect(settingsSections).toContain('<InterfaceSettings :config="config" />')
    expect(settingsSections).toContain('data-config-field="to"')
    expect(activeSectionSource(settingsSections, 'settings-general')).not.toContain('<InterfaceSettings :config="config" />')
    expect(activeSectionSource(settingsSections, 'settings-interface')).toContain('<InterfaceSettings :config="config" />')
    expect(activeSectionSource(settingsSections, 'settings-interface')).toContain('id="settings-interface"')
    expect(settingsGroupTitles(interfaceSettings)).toEqual([
      "translateLegacy('界面与弹窗')",
      "t('settings.interface.popupLayout.label')",
      "t('settings.interface.font.label')",
    ])
    expect(interfaceSettings).not.toContain('interface-font-advanced')
    expect(interfaceSettings).toContain('interface-font-card-status')
    expect(interfaceSettings).toContain('clearInterfaceFont')
    expect(interfaceSettings).toContain('ElMessageBox.confirm')
    expect(interfaceSettings).toContain("props.config.interfaceFont = 'system'")
    expect(interfaceSettings).toContain('<TranslationLoadingStyleSettings :config="props.config" />')
    expect(interfaceSettings.indexOf('<TranslationLoadingStyleSettings')).toBeLessThan(interfaceSettings.indexOf('t(\'settings.interface.popupLayout.label\')'))
    expect(source('src/features/settings/ui/TranslationLoadingStyleSettings.vue')).toContain("t('settings.interface.animationLoading.label')")
    expect(interfaceSettings).toContain('interfaceSkinOptions')
    expect(interfaceSettings).toContain('interfaceSkinGroups')
    expect(interfaceSettings).toContain('groupedSkinOptions')
    expect(interfaceSettings).toContain('PopupLayoutEditor')
    expect(interfaceSettings).toContain('PopupLayoutPreview')
    expect(interfaceSettings).toContain('data-popup-layout-workbench')
    expect(interfaceSettings).toContain('data-popup-layout-tab="popupModule"')
    expect(interfaceSettings).toContain('data-popup-layout-tab="quickFeature"')
    expect(interfaceSettings).toContain(':order="props.config.popupModuleOrder"')
    expect(interfaceSettings).toContain(':order="props.config.popupQuickFeatureOrder"')
    expect(interfaceSettings).toContain('@update:visibility="setPopupModuleVisibility"')
    expect(interfaceSettings).toContain('withInterfaceVisibility(')
    expect(interfaceSettings).toContain('withPopupQuickFeatureVisibility(')
    expect(interfaceSettings).toContain('popupModuleOptions.map')
    expect(interfaceSettings).toContain('popupQuickFeatureOptions.map')
    expect(interfaceSettings).toContain('class="interface-skin-option"')
    expect(interfaceSettings).toContain('<template #copy>')
    expect(interfaceSettings).toContain('<InterfaceSkinPreview')
    expect(interfaceSettings).toContain('selectedSkinOption')
    expect(interfaceSettings).toContain(':aria-label="translateLegacy(\'弹窗风格\')"')
    expect(interfaceSettings).toContain('const {t, translateLegacy} = useUiI18n()')
    expect(settingsItem).toContain('<slot name="copy">')
    expect(interfaceSkinPreview).toContain('class="interface-skin-live-preview"')
    expect(interfaceSkinPreview).toContain(':data-preview-skin="skin.value"')
    expect(interfaceSkinPreview).toContain('class="preview-language-pair"')
    expect(interfaceSkinPreview).toContain('class="preview-service"')
    expect(interfaceSkinPreview).not.toContain('<img')
    expect(popupLayoutPreview).toContain('data-preview-popup-module="translation"')
    expect(popupLayoutPreview).toContain(':data-preview-quick-feature="feature.id"')
    expect(popupLayoutPreview).toContain('siteModuleNestedInTranslation')
    expect(popupLayoutPreview).toContain('editScope')
    expect(popupLayoutPreview).not.toContain('<img')
    expect(interfaceSettings).toContain("t('settings.interface.popupLayout.label')")
    expect(interfaceSettings).toContain("t('settings.interface.popupLayout.moduleTab')")
    expect(interfaceSettings).toContain("t('settings.interface.popupLayout.featureTab')")
    expect(interfaceSettings).toContain("t('settings.interface.popupLayout.addFeatureSection')")
    expect(interfaceSettings).toContain('@update:module-order="setPopupModuleOrder"')
    expect(interfaceSettings).toContain('@update:quick-feature-order="setPopupQuickFeatureOrder"')
    expect(popupLayoutEditor).toContain('data-popup-layout-editor')
    expect(popupLayoutEditor).toContain('data-popup-quick-feature-editor')
    expect(popupLayoutEditor).toContain('data-popup-quick-feature-layout')
    expect(popupLayoutEditor).toContain('draggable="true"')
    expect(popupLayoutEditor).toContain('@keydown.up.prevent')
    expect(popupLayoutEditor).toContain('@keydown.down.prevent')
    expect(popupLayoutEditor).toContain("import {useUiI18n} from '@/src/ui/i18n'")
    expect(popupLayoutEditor).toContain('`${props.copyPrefix}.${suffix}`')
    expect(popupLayoutEditor).toContain('popup-layout-hidden-section')
    expect(popupLayoutEditor).toContain("copy('hideAria'")
    expect(popupLayoutEditor).toContain("copy('addAria'")
    expect(popupLayoutEditor).not.toContain('<el-switch')
    expect(popupLayoutPreviewItem).toContain('layout-preview-drag-handle')
    expect(popupLayoutPreviewItem).toContain('data-preview-action')
    expect(popupLayoutPreviewItem).toContain('controller.move')
    expect(popupLayoutReorder).toContain('reorderVisibleSlots')
    expect(popupLayoutReorder).toContain('visibleIds')
    expect(popupLayoutReorder).toContain('event.dataTransfer')
    expect(popupSiteRule).toContain('data-popup-module="siteRule"')
    expect(popupEntry).toContain("@/src/ui/styles/interface-skins.css")
    expect(optionsEntry).toContain("@/src/ui/styles/interface-skins.css")
    expect(popupHtml).toContain('class="popup-page"')
    expect(skinStyles).toContain('body.popup-page')
    expect(skinStyles).toContain('data-popup-height="content"')
    expect(skinStyles).toContain('min-height: 0')
    const nonDefaultSkins = ['minimal', 'compact', 'contrast', 'cheese', 'ocean', 'matcha', 'sakura', 'emoji', 'midnight', 'paper', 'aurora', 'arcade', 'sunset']
    for (const skin of nonDefaultSkins) {
      expect(skinStyles).toContain(`./interface-skins/${skin}.css`)
      expect(source(`src/ui/styles/interface-skins/${skin}.css`)).toContain(`data-interface-skin="${skin}"`)
    }
    expect(skinStyles).toContain('./interface-skins/palette.css')
    expect(skinStyles).not.toContain('./interface-skins/plain.css')
    expect(skinStyles).not.toContain('./interface-skins/soft.css')
    expect(minimalSkinStyles).toContain('data-interface-skin="minimal"')
    expect(minimalSkinStyles).toContain('overflow-wrap: anywhere')
    expect(minimalSkinStyles).not.toContain('.beta-badge')
    expect(paletteSkinStyles).not.toContain('.beta-badge')
    expect(minimalSkinStyles).toContain('opacity: .78')
    expect(minimalSkinStyles).not.toContain('saturate(')
    expect(minimalSkinStyles).toContain('background: color-mix(in srgb, var(--brand) 16%, var(--surface-soft))')
    expect(minimalSkinStyles).toContain('background: color-mix(in srgb, var(--brand) 5%, var(--surface-soft))')
    expect(minimalSkinStyles).toContain('.translate-button.translated .translate-hotkey')
    expect(paletteSkinStyles).toContain('data-interface-skin-kind="palette"')
    expect(paletteSkinStyles).toContain('.settings-card .service-catalog')
    expect(paletteSkinStyles).toContain('.image-ocr-recommendation')
    expect(paletteSkinStyles).toContain('.settings-card.vocabulary-view .vocabulary-book')
    expect(paletteSkinStyles).toContain('--el-bg-color: var(--surface)')
    expect(interfaceAppearance).toContain('dataset.interfaceSkinKind = skin.kind')
    expect(interfaceAppearance).toContain("style.setProperty('--interface-popup-width'")
    expect(settingsSections).toContain("const ModelUsageDashboard = defineAsyncComponent(() => import('@/src/features/model-usage/public').then(module => module.ModelUsageDashboard))")
    expect(settingsSections).toContain("v-show=\"props.activeSection === 'settings-model-usage'\"")
    expect(settingsSections).toContain(":active=\"props.activeSection === 'settings-model-usage'\"")
    expect(modelUsagePublic).toContain("from './ui/ModelUsageDashboard.vue'")
    expect(modelUsageDashboard).toContain('id="settings-model-usage"')
    expect(modelUsageDashboard).toContain("type: 'modelUsage'")
    expect(modelUsageDashboard).toContain("action: 'query'")
    expect(modelUsageDashboard).toContain("action: 'list'")
    expect(modelUsageDashboard).not.toContain("action: 'export'")
    expect(modelUsageDashboard).not.toContain("action: 'import'")
    expect(modelUsageDashboard).toContain("action: 'reset'")
    expect(modelUsageDashboard).toContain('完整备份与恢复统一在“备份与恢复”中管理')
    expect(modelUsageDashboard).not.toContain('导出全部数据')
    expect(modelUsageDashboard).not.toContain('导入模型用量数据')
    expect(modelUsageDashboard).not.toContain('type="file"')
    expect(modelUsageDashboard).toContain('<style scoped src="./model-usage-dashboard.css"></style>')
    expect(modelUsageDashboard).toContain('snapshot.value?.selected.filter')
    expect(modelUsageDashboard).toContain('{{ appliedRangeLabel }} · {{ appliedScopeLabel }}')
    expect(modelUsageDashboard).toContain('<em v-if="loading">正在更新…</em>')
    expect(modelUsageDashboard).toContain('<el-select v-model="selectedService"')
    expect(modelUsageDashboard).toContain('averageUncachedInputTokensPerCacheReportedRequest')
    expect(modelUsageDashboard).toContain('averageCachedInputTokensPerCacheReportedRequest')
    expect(modelUsageDashboard).toContain('averageOutputTokensPerCacheReportedRequest')
    expect(modelUsageDashboard).toContain('输入（无缓存）')
    expect(modelUsageDashboard).toContain('<em><span>占比</span> {{ formatUsageRate(selectedTotals.cachedInputTokenShare) }}</em>')
    expect(modelUsageDashboard).toContain('usage-average-grid')
    expect(modelUsageDashboard).toContain('按${option.label}排序')
    expect(modelUsageDashboard).toContain("{key: 'requests', label: '次数'}")
    expect(modelUsageDashboard).toContain("{key: 'cache', label: '缓存'}")
    expect(modelUsageDashboard).toContain('usage-breakdown-requests')
    expect(modelUsageDashboard).toContain('usage-breakdown-total')
    expect(modelUsageDashboard).toContain(':class="{ active: appliedFilter.serviceId === row.serviceId && appliedFilter.model === row.model }"')
    expect(modelUsageDashboard).toContain('if (totalTokens <= 0) return 0')
    expect(modelUsageDashboard).not.toContain('<span>模型缓存</span>')
    expect(modelUsageDashboard).not.toContain('缓存明细覆盖')
    expect(modelUsageDashboard).toContain('次{{ selectedTotals.cacheReportedRequests < selectedTotals.reportedTokenRequests ? \'可计算\' : \'\' }}请求命中')
    expect(modelUsageDashboard).toContain('usage-composition-card')
    expect(modelUsageDashboard).toContain(':data-segment="segment.key"')
    expect(modelUsageDashboard).toContain('<details class="usage-average-card">')
    expect(modelUsageDashboard).toContain('<details v-if="hasSelectedUsage" class="usage-card usage-request-log-card"')
    expect(modelUsageDashboard).toContain('<strong>请求记录</strong>')
    expect(modelUsageDashboard).toContain('class="usage-refresh-button"')
    expect(modelUsageDashboard).toContain('aria-label="趋势指标"')
    expect(modelUsageDashboard).toContain(':aria-pressed="trendMetric === \'tokens\'"')
    expect(modelUsageDashboard).toContain(':aria-pressed="trendMetric === \'requests\'"')
    expect(modelUsageDashboard).toContain('class="usage-trend-inspector" aria-live="polite"')
    expect(modelUsageDashboard).toContain('@keydown="handleTrendKeydown($event, index)"')
    expect(modelUsageDashboard).toContain('输入命中率 ${formatUsageRate(requestCacheRate(item))}')
    expect(modelUsageDashboard).toContain('缓存创建（服务商上报）')
    expect(modelUsageDashboard).toContain('requestPageSizeOptions')
    expect(modelUsageDashboard).toContain('第 {{ requestPageIndex + 1 }} / {{ requestPageCount }} 页')
    expect(modelUsageDashboard).toContain('loadNextRequestPage')
    expect(modelUsageDashboard).toContain('@click="loadRequestPage(requestLogRetryPageIndex)"')
    expect(modelUsageDashboard).toContain('requestLogRetryPageIndex.value = pageIndex')
    expect(modelUsageDashboard).toContain('if (pageIndex === 0) requestLogTotalCount.value = response.data.totalCount')
    expect(modelUsageDashboard).toContain('不保存原文、译文、提示词、网页地址、API Key、请求体或响应正文')
    expect(modelUsageDashboard).not.toContain('MODEL_USAGE_TRANSFER_FORMAT')
    expect(modelUsageDashboard).toContain('handleRangeKeydown')
    expect(modelUsageDashboard).toContain(':tabindex="range === option.value ? 0 : -1"')
    expect(modelUsageDashboard).toContain("if (event.key === 'Home') nextIndex = 0")
    expect(modelUsageDashboard).toContain('<Teleport to="body">')
    expect(modelUsageDashboard).toContain('ref="resetCancelButton"')
    expect(modelUsageDashboard).toContain("settingsApp?.setAttribute('inert', '')")
    expect(modelUsageDashboard).toContain("querySelectorAll<HTMLButtonElement>('button:not(:disabled)')")
    expect(modelUsageDashboard).toContain("document.addEventListener('visibilitychange', handleVisibilityChange)")
    expect(modelUsageDashboard).toContain("watch(() => props.active")
    expect(settingsSections).toContain('id="settings-translation"')
    expect(settingsSections).not.toContain('id="settings-webpage"')
    expect(settingsSections).not.toContain('id="settings-shortcuts"')
    expect(settingsSections).toContain('<ConfigManagement')
    expect(settingsSections).toContain('<SettingsGroup')
    expect(settingsSections).toContain("const QuickTranslationProfiles = defineAsyncComponent(() => import('./QuickTranslationProfiles.vue'))")
    expect(quickTranslationProfiles).toContain("type QuickTranslationProfile")
    expect(quickTranslationProfiles).toContain('MAX_QUICK_TRANSLATION_PROFILES')
    expect(quickTranslationProfiles).toContain('CustomHotkeyInput')
    expect(quickTranslationProfiles).toContain('withCustomOpenAIServiceOptions')
    expect(quickTranslationProfiles).toContain('@media (max-width: 640px)')
    expect(quickTranslationProfiles).toContain('const creatingProfile = ref(false)')
    expect(quickTranslationProfiles).toContain('@click="addProfile($event)"')
    expect(quickTranslationProfiles).toContain(':validate="validateProfileHotkey"')
    expect(quickTranslationProfiles).not.toContain('class="empty-state"')
    expect(quickTranslationProfiles).not.toContain(':disabled="!profile.service"')
    expect(quickTranslationProfiles).toContain(":placeholder=\"t('quickTranslation.followDefault', {value: languageLabel(config.to)})\"")
    expect(quickTranslationProfiles).toContain('const {language, t, translateLegacy} = useUiI18n()')
    expect(translationShortcutSettings).toContain("t('quickTranslation.conflictProfile', {group})")
    expect(customHotkeyInput).toContain("if (event.key === 'Escape')")
    expect(customHotkeyInput.indexOf("if (event.key === 'Escape')"))
      .toBeLessThan(customHotkeyInput.indexOf('if (!isRecording.value) return;'))
    expect(customHotkeyInput).toContain("watch(dialogVisible, (visible) => {")
    expect(customHotkeyInput).toContain("currentHotkey.value = props.currentValue || '';")
    expect(customHotkeyInput).toContain('pressedKeys.value.clear();')
    expect(customHotkeyInput).toContain('validate?: (hotkey: string) => string;')
    expect(customHotkeyInput).toContain("const contextualError = props.validate?.(hotkeyString) || '';")
    expect(customHotkeyInput).not.toContain("emit('confirm', currentHotkey.value);\n  emit('update:modelValue', false);")
    expect(customHotkeyInput).toContain('!focusable.includes(activeElement)')
    expect(customHotkeyInput).toContain('(event.shiftKey ? last : first).focus();')
    expect(settingsSections).toContain(':validate="validateCustomFullPageHotkey"')
    expect(settingsSections).toContain(':validate="validateCustomMouseHotkey"')
    expect(settingsSections).not.toContain("'Shift+Z'")
    expect(settingsSections).toContain("useTranslationShortcutSettings(config)")
    expect(translationShortcutSettings).toContain('inputBoxTranslationTriggerHotkey(value)')
    expect(quickTranslationProfiles).toContain('inputBoxTranslationTriggerHotkey(props.config.inputBoxTranslationTrigger)')
    expect(translationShortcutSettings).toContain('previousFullPageHotkey')
    expect(translationShortcutSettings).toContain('previousSelectionTrigger')
    expect(configManagement).toContain('<LocalDataManagement :config="config" />')
    expect(configManagement.indexOf('<LocalDataManagement :config="config" />'))
      .toBeLessThan(configManagement.indexOf('<header class="history-heading">'))
    expect(configManagement).toContain('<h2>设置历史</h2>')
    expect(configManagement).toContain('<h2 id="automatic-backup-title">自动设置快照</h2>')
    expect(configManagement).not.toContain('仅迁移配置')
    expect(configManagement).not.toContain('config-transfer-dialog')
    expect(configManagement).not.toContain('openExportDialog')
    const transferActions = localDataManagement.match(/<div class="transfer-actions">([\s\S]*?)<\/div>/u)?.[1]
    expect(transferActions).toBeDefined()
    expect(transferActions?.match(/<el-button\b/gu)).toHaveLength(2)
    expect(transferActions).toContain('>导出备份</el-button>')
    expect(transferActions).toContain('>从备份恢复</el-button>')
    expect(configManagement).not.toContain('prepareConfigForExport(props.config)')
    expect(configManagement).not.toContain('persist-credentials-switch')
    expect(configManagement).not.toContain('跨浏览器重启保存 API 凭据')
    expect(configManagement).not.toContain('<SettingsGroup title="凭据安全"')
    expect(configManagement).not.toContain('type="file"')
    expect(configManagement).not.toContain('downloadConfig')
    expect(localDataManagement).toContain('title="完整备份"')
    expect(localDataManagement).not.toContain('分别管理')
    expect(localDataManagement).toContain('createFluentReadDataBackup')
    expect(localDataManagement).toContain('openRestoreSource($event)')
    expect(localDataManagement).toContain('data-testid="restore-source-dialog"')
    expect(localDataManagement).toContain('粘贴旧版配置 JSON')
    expect(localDataManagement).toContain('previewPastedImport')
    expect(localDataManagement).toContain('@click="exportCompleteBackup($event)"')
    expect(localDataManagement).toContain('@click="chooseImport($event)"')
    expect(localDataManagement).toContain('@click="previewPastedImport($event)"')
    expect(localDataManagement).toContain('await focusTriggerAfterBusy(trigger)')
    expect(localDataManagement).toContain('restoreSourceVisible.value && !importPreviewVisible.value')
    expect(localDataManagement).toContain('activeElement === document.body || activeElement === document.documentElement')
    expect(localDataManagement).toContain('prepareHydratedConfigForExport()')
    expect(localDataManagement).toContain('credentialMode: resolveBackupConfigCredentialMode(target.backup)')
    expect(localDataManagement).toContain("credentialIntent: target.kind === 'complete' && usesExactCredentialReplacement(target.backup)")
    expect(localDataManagement).toContain("? 'exact'")
    expect(localDataManagement).toContain(": 'changed-fields'")
    expect(localDataManagement).toContain('computed(() => prepareImportedConfig(pendingImport.value, props.config))')
    expect(localDataManagement).toContain('const targetConfig = prepareImportedConfig(target, props.config)')
    expect(localDataManagement).toContain("target?.kind === 'config'")
    expect(localDataManagement).not.toContain('dataset-row')
    expect(localDataManagement).not.toContain('按事件 ID')
    expect(localDataManagement).not.toContain('三个独立数据库')
    expect(serviceConfiguration).toContain(':data-service-configuration-service="service"')
    expect(serviceConfiguration).toContain('<ApiKeyList')
    expect(serviceConfiguration).not.toContain('class="credential-warning"')
    expect(serviceConfiguration).not.toContain('默认仅保留在当前浏览器会话')
    expect(settingsSections).not.toContain('fluentReadImageOcrDownload')
    expect(settingsSections).toContain('<InputTranslationSettings')
    expect(inputTranslationSettings).toContain("t('inputTranslation.triggerDescription')")
    expect(inputTranslationSettings).toContain('data-testid="input-translation-settings"')
    expect(inputTranslationMessages).toContain('"inputTranslation.triggerDescription"')
    expect(inputTranslationMessages).toContain('密码框和富文本编辑器不会参与')
    expect(settingsSections).not.toContain('任何文本输入框')
    expect(settingsSections).toContain('@/src/ui/components/CustomHotkeyInput.vue')
    expect(popup).toContain('@/src/ui/components/ServiceIcon.vue')
    expect(popup).toContain('@/src/platform/browser/ids')
    expect(popup).toContain('requestConfigPatch')
    expect(popup).toContain('config.interfaceVisibility.popupQuickFeatures')
    expect(popup).toContain('config.value.interfaceVisibility.popupSiteRule')
    expect(popup).toContain('config.interfaceVisibility.popupFooter')
    expect(popup).toContain('v-for="moduleId in visiblePopupModuleOrder"')
    expect(popup).toContain('config.value.popupModuleOrder.filter')
    expect(popup).toContain('config.value.popupQuickFeatureOrder.filter')
    expect(popup).toContain('config.value.popupQuickFeatureVisibility[featureId]')
    expect(popup).toContain('v-for="feature in visiblePopupQuickFeatures"')
    expect(popup).toContain(':data-popup-quick-feature="feature.id"')
    expect(popup).toContain('Record<PopupQuickFeatureId, PopupQuickFeatureViewModel>')
    expect(popup).toContain('data-popup-module="translation"')
    expect(popup).toContain('data-popup-module="quickFeatures"')
    expect(popup).toContain('data-popup-module="footer"')
    expect(popup).toContain('siteModuleNestedInTranslation')
    expect(popup).toContain(':data-popup-module-last="lastVisiblePopupModule === \'footer\'"')
    expect(popup).toContain("import PopupSiteRule from './PopupSiteRule.vue'")
    expect(popupStyles).toContain('.popup-content > [data-popup-module] + .hero-card')
    expect(popupStyles).toContain('footer[data-popup-module-last="false"]')
    expect(minimalSkinStyles).toContain('.popup-content > footer[data-popup-module-last="true"]')
    expect(popup).toContain('popupUsesContentHeight')
    expect(popup).toContain('interfaceSkinUsesContentHeight(config.value.interfaceSkin)')
    expect(popup).not.toContain("config.value.interfaceSkin === 'minimal'")
    expect(popup).toContain('dataset.popupHeight')
    expect(popup).toContain('applyInterfaceSkin')
    expect(popup).not.toMatch(/\bsaveConfig\b/u)
    expect(popup).not.toMatch(/(?:!tab\?\.id|filter\(tab\s*=>\s*tab\.id\))/u)
    expect(settingsSections).toContain('@/src/platform/browser/ids')
    expect(settingsSections).not.toMatch(/if\s*\(\s*!?tab\.id\s*\)/u)
  })

  it('keeps the Firefox persistence fixture aligned with the current data-section contract', () => {
    const firefoxPersistence = source('scripts/run-firefox-config-persistence.mjs')

    expect(firefoxPersistence).toContain('button[data-section="settings-data"]')
    expect(firefoxPersistence).toContain('备份与恢复导航不存在')
    expect(firefoxPersistence).toContain('result.historyCases.count > 10')
    expect(firefoxPersistence).not.toContain("textContent?.includes('配置管理')")
    expect(firefoxPersistence).not.toContain('配置管理导航不存在')
    expect(firefoxPersistence).not.toContain('result.historyCases.count > 5')
  })

  it('filters Chrome-only providers in every options selector without overwriting old values', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const translationCenter = source('src/features/translation-center/ui/TranslationCenter.vue')

    expect(settings).toContain('withCustomOpenAIServiceOptions(')
    expect(settings).toContain('filterAvailableTranslationServices(serviceOptionsWithCustomProviders.value)')
    expect(settings).toContain('selectedTextServiceUnavailableMessage')
    expect(settings).toContain('Chrome内置AI翻译（当前浏览器不可用）')
    expect(translationCenter).toContain('filterAvailableTranslationServices(withCustomOpenAIServiceOptions(')
    expect(translationCenter).toContain('getCustomOpenAIProviderModels(customOpenAIProviders.value')
    expect(translationCenter).toContain('原配置会保留')
    expect(translationCenter).toContain('if (!isTranslationServiceAvailable(service)) return [service]')
  })

  it('uses saved dynamic service profiles across comparison, history, usage and shared icons', () => {
    const translationCenter = source('src/features/translation-center/ui/TranslationCenter.vue')
    const configManagement = source('src/features/settings/ui/ConfigManagement.vue')
    const modelUsageDashboard = source('src/features/model-usage/ui/ModelUsageDashboard.vue')
    const serviceIcon = source('src/ui/components/ServiceIcon.vue')

    expect(translationCenter).toContain('isConfiguredCustomOpenAIProvider(customOpenAIProviders.value, item.value)')
    expect(configManagement).toContain('getCustomOpenAIProviderLabel(value.customOpenAIProviders, value.service)')
    expect(modelUsageDashboard).toContain('getCustomOpenAIProviderLabel(customOpenAIProviders.value, serviceId)')
    expect(modelUsageDashboard).toContain('const unsubscribeConfig = subscribeConfig(nextConfig =>')
    expect(serviceIcon).toContain('isCustomOpenAIProviderId(props.service)')
    expect(serviceIcon).toContain('v-else-if="isCustomOpenAIService"')
  })

  it('keeps dynamic OpenAI-compatible profiles editable in userscript settings', () => {
    const userscriptSettings = source('userscript/SettingsPanel.vue')

    expect(userscriptSettings).toContain('withCustomOpenAIServiceOptions(')
    expect(userscriptSettings).toContain('draft.value.customOpenAIProviders')
    expect(userscriptSettings).toContain('selectedCustomOpenAIProvider.value?.models')
    expect(userscriptSettings).toContain('isCustomOpenAIService.value || servicesType.isUseModel')
    expect(userscriptSettings).toContain('v-model.trim="customOpenAIEndpoint"')
    expect(userscriptSettings).toContain('provider.id === service ? {...provider, endpoint} : provider')
    expect(userscriptSettings).toContain('if (service === services.custom) draft.value.custom = endpoint')
    expect(userscriptSettings).toContain('draft.value.customModels[service] = normalizeCustomOpenAIModels')
    expect(userscriptSettings).toContain('function removeSelectedCustomModel()')
    expect(userscriptSettings).toContain('删除当前自定义模型')
    expect(userscriptSettings).not.toContain('v-model.trim="draft.custom" inputmode="url"')
    const serviceFieldsetStart = userscriptSettings.indexOf('<legend>翻译服务</legend>')
    const serviceFieldsetEnd = userscriptSettings.indexOf('</fieldset>', serviceFieldsetStart)
    const serviceFieldsetSource = userscriptSettings.slice(serviceFieldsetStart, serviceFieldsetEnd)
    const advancedRequestStart = userscriptSettings.indexOf('<summary>高级 AI 请求设置</summary>')
    const advancedRequestEnd = userscriptSettings.indexOf('</details>', advancedRequestStart)
    const advancedRequestSource = userscriptSettings.slice(advancedRequestStart, advancedRequestEnd)
    expect(serviceFieldsetStart).toBeGreaterThanOrEqual(0)
    expect(serviceFieldsetEnd).toBeGreaterThan(serviceFieldsetStart)
    expect(serviceFieldsetSource).not.toContain('Thinking')
    expect(advancedRequestStart).toBeGreaterThanOrEqual(0)
    expect(advancedRequestEnd).toBeGreaterThan(advancedRequestStart)
    expect(advancedRequestSource).toContain('aria-label="当前模型是否启用 Thinking"')
    expect(advancedRequestSource).toContain('v-model="selectedModelThinking"')
    expect(userscriptSettings).not.toContain('customModelThinking')
  })

  it('offers selectable paragraph loading animations with true runtime previews', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const interfaceSettings = source('src/features/settings/ui/InterfaceSettings.vue')
    const picker = source('src/features/settings/ui/TranslationLoadingStyleSettings.vue')
    const preview = source('src/ui/components/TranslationLoadingPreview.vue')
    const indicator = source('src/ui/translationLoadingIndicator.ts')
    const pageStyles = source('src/app/content/page.css')
    const userscriptSettings = source('userscript/SettingsPanel.vue')
    const userscriptSmoke = source('scripts/run-userscript-smoke-test.cjs')

    expect(settings).not.toContain('<TranslationLoadingStyleSettings :config="config" />')
    expect(interfaceSettings).toContain('<TranslationLoadingStyleSettings :config="props.config" />')
    expect(picker).toContain('v-for="option in translationLoadingStyleOptions"')
    expect(picker).toContain('role="radiogroup"')
    expect(picker).toContain('<TranslationLoadingPreview')
    expect(picker).toContain(':animated="props.config.animations"')
    expect(picker).toContain("import { useUiI18n } from '@/src/ui/i18n'")
    expect(picker).toContain('const { t } = useUiI18n()')
    expect(picker).toContain('t(option.labelKey)')
    expect(picker).toContain('t(option.descriptionKey)')
    expect(picker).toContain("settings.interface.animationLoading.label")
    expect(picker).not.toContain('{{ option.label }}')
    expect(picker).not.toContain('{{ option.description }}')
    expect(preview).toContain('createTranslationLoadingIndicator(document')
    expect(indicator).toContain("attachShadow({mode: 'closed'})")
    expect(indicator).toContain("['animation', 'none']")
    expect(indicator).toContain("['all', 'initial']")
    expect(indicator).toContain(':host::before')
    expect(indicator).toContain('content: none !important')
    expect(indicator).not.toContain("classList.add('static')")
    expect(pageStyles).not.toMatch(/@keyframes\s+spin\b/u)
    expect(userscriptSettings).toContain('v-model="draft.translationLoadingStyle"')
    expect(userscriptSettings).toContain(':disabled="!draft.animations"')
    expect(userscriptSettings).toContain('<TranslationLoadingPreview :loading-style="draft.translationLoadingStyle"')
    expect(userscriptSettings).toContain('aria-label="当前动画参考"')
    expect(userscriptSmoke).toContain("translationLoadingStyle: 'orbit'")
    expect(userscriptSmoke).toContain('userscriptLoadingStyle')
    expect(userscriptSmoke).toContain('HOST PAGE')
  })

  it('persists translation-center edits as precise field patches', () => {
    const translationCenter = source('src/features/translation-center/ui/TranslationCenter.vue')

    expect(translationCenter).toContain("persistTranslationCenterConfig('source')")
    expect(translationCenter).toContain("persistTranslationCenterConfig('target')")
    expect(translationCenter).toContain("persistTranslationCenterConfig('services')")
    expect(translationCenter).toContain("persistTranslationCenterConfig('source', 'target')")
    expect(translationCenter).toContain('const requestedFields = new Set(fields)')
    expect(translationCenter).toContain('if (Object.keys(patch).length === 0) return')
  })

  it('uses patches for ordinary autosaves and hands pending popup and settings chains to the config service on exit', () => {
    const popup = source('src/app/popup/PopupApp.vue')
    const settings = source('src/features/settings/ui/SettingsSections.vue')

    for (const content of [popup, settings]) {
      expect(content).toContain('requestConfigPatch')
      expect(content).toContain('persistConfigPatch(snapshot)')
      expect(content).not.toContain('replace 作为队列 flush/barrier')
    }
    expect(settings).not.toContain('requestConfigSave')
    expect(settings).not.toContain('persistConfigReplace(config.value)')
    expect(settings).toContain('persistConfigPatch(config.value)')
    expect(settings).toContain('handoffPendingConfigPatches(sendConfigMessage, sendConfigMessage)')
    expect(settings).toContain("window.addEventListener('beforeunload', persistOnPageExit);")
    expect(settings).toContain("window.removeEventListener('beforeunload', persistOnPageExit);")
    expect(settings).toContain("window.addEventListener('pagehide', saveOnPageHide);")
    expect(popup).not.toContain('requestConfigSave')
    expect(popup).toContain('persistConfigPatch(config.value)')
    expect(popup).toContain('handoffPendingConfigPatches(sendConfigMessage, sendConfigMessage)')
  })

  it('hydrates settings drafts through normalizeConfig so nested edits cannot mutate the runtime baseline', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')

    expect(settings).toContain('Object.assign(config.value, normalizeConfig(nextConfig));')
    expect(settings).toContain('Object.assign(config.value, normalizeConfig(runtimeConfig));')
    expect(settings).not.toContain('Object.assign(config.value, nextConfig);')
    expect(settings).not.toContain('Object.assign(config.value, runtimeConfig);')
  })

  it('persists before remote tests while starting Chrome model preparation inside click activation', () => {
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const testConnectionStart = serviceConfiguration.indexOf('async function testConnection(): Promise<void>')
    const testConnectionEnd = serviceConfiguration.indexOf('function resetCustomTemplate(): void', testConnectionStart)
    const testConnection = serviceConfiguration.slice(testConnectionStart, testConnectionEnd)
    const chromePreparationIndex = testConnection.indexOf('prepareChromeTranslationInPage({')
    const waitIndex = testConnection.indexOf('await waitForConnectionStep(waitForConfigPersistenceQueue(), CONNECTION_CONFIG_WAIT_TIMEOUT_MS')
    const saveIndex = testConnection.indexOf('await waitForConnectionStep(requestConfigSave(config.value')
    const connectionTestIndex = testConnection.indexOf('type: CONNECTION_TEST_MESSAGE')

    expect(testConnectionStart).toBeGreaterThanOrEqual(0)
    expect(testConnectionEnd).toBeGreaterThan(testConnectionStart)
    expect(chromePreparationIndex).toBeGreaterThanOrEqual(0)
    expect(chromePreparationIndex).toBeLessThan(waitIndex)
    expect(waitIndex).toBeGreaterThanOrEqual(0)
    expect(saveIndex).toBeGreaterThan(waitIndex)
    expect(connectionTestIndex).toBeGreaterThan(saveIndex)
    expect(testConnection).toContain('testedService === services.chromeTranslator')
    expect(testConnection).toContain('if (chromePreparation)')
    expect(testConnection).toContain('service: testedService')
  })

  it('uses the configured language pair and exposes official Chrome help', () => {
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const chromePreparation = source('src/features/settings/model/chromeTranslationPreparation.ts')

    expect(serviceConfiguration).toContain("t('settings.services.keys.checkConnection')")
    expect(serviceConfiguration).toContain("t('settings.services.chromePreparation.titleReady')")
    expect(serviceConfiguration).not.toContain('class="setup-status"')
    expect(serviceConfiguration).toContain("const { language, t, translateLegacy } = useUiI18n()")
    expect(serviceConfiguration).not.toContain('data-chrome-preparation-source')
    expect(serviceConfiguration).not.toContain('chromePreparationSourceLanguage')
    expect(serviceConfiguration).toContain('from: pair.sourceLanguage')
    expect(serviceConfiguration).toContain('chromeTranslationPreparationStore')
    expect(serviceConfiguration).toContain('data-chrome-preparation-help')
    expect(serviceConfiguration).toContain('helpSummary')
    expect(serviceConfiguration).toContain("t('settings.services.chromePreparation.sourceDescription')")
    expect(serviceConfiguration).toContain('CHROME_PREPARATION_TIMEOUT_MS = 300_000')
    expect(serviceConfiguration).toContain('activeChromePreparation?.abort()')
    expect(serviceConfiguration).toContain("'settings.services.chromePreparation.success'")
    expect(serviceConfiguration).toContain('ChromeTranslationPreparationError')
    expect(serviceConfiguration).toContain('CHROME_PREPARATION_ERROR_KEYS[error.code]')
    expect(serviceConfiguration).not.toContain('Chrome 本地翻译已全部准备')
    expect(chromePreparation).toContain('再次点击“准备 Chrome 本地翻译”继续准备')
    expect(chromePreparation).toContain("'user-activation-required'")
  })

  it('uses bounded model picking and atomic custom-service drafts in settings', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const catalog = source('src/features/settings/ui/services/ServiceCatalog.vue')
    const modelPicker = source('src/features/settings/ui/services/ModelPicker.vue')
    const providerDialog = source('src/features/settings/ui/services/CustomOpenAIProviderDialog.vue')
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const apiKeyList = source('src/features/settings/ui/services/ApiKeyList.vue')
    const promptEditor = source('src/features/settings/ui/services/PromptTemplateEditor.vue')

    expect(catalog).toContain('data-testid="custom-service-add"')
    expect(catalog).toContain("t('settings.services.library.add')")
    expect(catalog).toContain('<ModelPicker')
    expect(catalog).not.toContain('model-grid expanded')
    expect(catalog).not.toContain('.model-grid.expanded')
    expect(modelPicker).toContain('popper-class="model-picker-popper"')
    expect(modelPicker).toContain('transition="model-picker-instant"')
    expect(modelPicker).toContain("import {ElPopover} from 'element-plus'")
    expect(modelPicker).toContain('<ElPopover')
    expect(modelPicker).toContain(':key="pickerContentKey"')
    expect(modelPicker).toContain('const pickerContentKey = computed(')
    expect(modelPicker).toContain('max-height: min(300px, 45vh)')
    expect(modelPicker).toContain('class="model-picker-chip"')
    expect(modelPicker).toContain('display: flex; flex-wrap: wrap')
    expect(modelPicker).toContain('.model-picker-chip.active')
    expect(modelPicker).toContain('pickerTrigger.value?.focus({preventScroll: true})')
    const removeModelStart = modelPicker.indexOf('function removeModel(model: string): void')
    const removeModelEnd = modelPicker.indexOf('\n}', removeModelStart)
    const removeModelSource = modelPicker.slice(removeModelStart, removeModelEnd)
    expect(removeModelSource).toContain("emit('remove', model)")
    expect(removeModelSource).toContain('closePicker()')
    expect(removeModelSource.indexOf('closePicker()'))
      .toBeLessThan(removeModelSource.indexOf("emit('remove', model)"))
    expect(modelPicker).toContain('@click.stop="removeModel(option.value)"')
    expect(modelPicker).toContain('opacity: 1 !important')
    expect(modelPicker).toContain('data-testid="custom-model-input"')
    expect(modelPicker).not.toContain('data-testid="custom-model-thinking"')
    expect(modelPicker).toContain("emit('add', model)")
    expect(modelPicker).not.toContain('Thinking')
    expect(catalog).not.toContain('data-testid="model-thinking-control"')
    expect(catalog).not.toContain('Thinking')
    const configurationGroup = (group: string) => {
      const start = serviceConfiguration.indexOf(`data-configuration-group="${group}"`)
      const nextGroup = serviceConfiguration.indexOf('data-configuration-group="', start + 1)
      const end = nextGroup >= 0 ? nextGroup : serviceConfiguration.indexOf('</section>', start)
      expect(start).toBeGreaterThanOrEqual(0)
      expect(end).toBeGreaterThan(start)
      return serviceConfiguration.slice(start, end)
    }
    const connectionGroup = configurationGroup('connection')
    expect(connectionGroup).toContain('data-deeplx-endpoint')
    const keysGroup = configurationGroup('keys')
    const translationGroup = configurationGroup('translation')
    const requestsGroup = configurationGroup('requests')
    const customRequestGroup = configurationGroup('custom-request')
    const outerAdvancedStart = serviceConfiguration.indexOf('data-testid="custom-service-advanced"')
    const outerAdvancedEnd = serviceConfiguration.indexOf('</details>', outerAdvancedStart)
    expect(outerAdvancedStart).toBeGreaterThanOrEqual(0)
    expect(outerAdvancedEnd).toBeGreaterThan(outerAdvancedStart)
    const outerAdvanced = serviceConfiguration.slice(outerAdvancedStart, outerAdvancedEnd)
    expect(serviceConfiguration).toContain('class="connection-card"')
    expect(keysGroup).toContain('data-api-key-rotation-setting')
    expect(keysGroup).toContain('data-api-key-auth-policy')
    expect(translationGroup).toContain('data-testid="model-thinking-control"')
    expect(translationGroup).toContain('<PromptTemplateEditor v-model="config.system_role[service]" role="system" />')
    expect(translationGroup).toContain('<PromptTemplateEditor v-model="config.user_role[service]" role="user" />')
    expect(requestsGroup).toContain('<RequestLimitSettings')
    expect(requestsGroup).toContain('v-if="compute.showDeepseekApiType"')
    expect(customRequestGroup).toContain('v-if="customProvider"')
    expect(customRequestGroup).toContain('v-if="compute.showCustomBody"')
    expect(outerAdvanced).toContain('class="advanced-groups"')
    expect(outerAdvanced).toContain('data-configuration-group="keys"')
    expect(outerAdvanced).toContain('data-configuration-group="translation"')
    expect(outerAdvanced).toContain('data-configuration-group="requests"')
    expect(outerAdvanced).toContain('data-configuration-group="custom-request"')
    expect(serviceConfiguration).toContain('<Teleport v-if="connectionActionTarget" :to="connectionActionTarget">')
    expect(catalog).toContain('class="hero-connection-action"')
    expect(apiKeyList).not.toContain('data-connection-test-button')
    expect(serviceConfiguration).toContain(':disabled="connectionTestBusy && !usesApiKeyList"')
    expect(serviceConfiguration.match(/<details[^>]*class="custom-advanced-settings"/gu) || []).toHaveLength(1)
    expect(serviceConfiguration).toContain('data-api-key-rotation-setting')
    expect(serviceConfiguration).toContain('displayedApiKeys')
    expect(serviceConfiguration).toContain(':allow-multiple="apiKeyRotationEnabled"')
    expect(apiKeyList).not.toContain("settings.services.keys.singleHelp")
    expect(apiKeyList).toContain('props.allowMultiple')
    expect(translationGroup).toContain(':model-value="selectedModelThinking"')
    expect(translationGroup).toContain("$emit('update:model-thinking', Boolean($event))")
    expect(modelPicker).toContain('model === CUSTOM_OPENAI_RESERVED_MODEL_ID')
    expect(providerDialog).toContain('data-testid="custom-service-dialog"')
    expect(providerDialog).not.toContain('data-testid="custom-service-model-thinking"')
    expect(providerDialog).not.toContain('Thinking')
    expect(providerDialog).toContain('const draft = reactive<CustomOpenAIProviderDraft>')
    expect(providerDialog).toContain("emit('submit', value)")
    expect(providerDialog).toContain('value.model === CUSTOM_OPENAI_RESERVED_MODEL_ID')
    expect(settings).toContain('createNextCustomOpenAIProviderId(')
    expect(settings).toContain('configurationService.value = id')
    expect(settings).toContain('configurationService.value = null')
    expect(settings).toContain('!getCustomOpenAIProvider(config.value.customOpenAIProviders, service)')
    expect(settings).toContain('removeCustomOpenAIProvider(')
    expect(settings).toContain('updateConfigAtomically((next) =>')
    expect(settings).toContain(':selected-model-thinking="selectedConfigurationModelThinking"')
    expect(settings).toContain('@update:model-thinking="updateSelectedConfigurationModelThinking"')
    expect(settings).toContain('withoutModelThinkingPreference(next.modelThinking, service, model)')
    expect(serviceConfiguration).not.toContain('v-model="config.customModel[service]"')
    expect(serviceConfiguration).not.toContain('v-show="compute.')
    expect(serviceConfiguration).toContain('v-if="compute.showMiniMaxRegion"')
    expect(serviceConfiguration).toContain('v-if="compute.showAI" class="advanced-group" data-configuration-group="translation"')
    expect(serviceConfiguration).toContain('<PromptTemplateEditor v-model="config.system_role[service]" role="system" />')
    expect(serviceConfiguration).toContain('<PromptTemplateEditor v-model="config.user_role[service]" role="user" />')
    expect(promptEditor).toContain('data-prompt-token')
    expect(promptEditor).toContain("{value: '{{to}}', label: '目标语言'}")
    expect(promptEditor).toContain("{value: '{{origin}}', label: '待翻译原文'}")
    expect(promptEditor).toContain('v-if="promptTokens.length"')
    expect(promptEditor).toContain("props.role === 'user'")
    expect(promptEditor).toContain('@mousedown.prevent')
  })

  it('puts service selection, webpage assistance and translated-text display in General', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const general = activeSectionSource(settings, 'settings-general')
    const services = activeSectionSource(settings, 'settings-services')
    const styles = sourceBody('src/features/settings/ui/settings-sections.css')

    expect(settingsGroupTitles(general)).toEqual(['选择翻译服务', '网页辅助'])
    expect(general).not.toContain('class="settings-subgroup-heading"')
    expect(general).not.toContain('id="translated-display-heading"')
    expect(general).toContain('data-testid="open-translation-settings"')
    expect(general).toContain('data-testid="open-floating-ball-settings"')
    expect(general).toContain("openSettingsSection('settings-translation', 'floating-ball-settings')")
    expect(general).toContain('data-testid="default-translation-service-card"')
    expect(general).toContain(':data-default-service="config.service"')
    expect(general).toContain('data-testid="translation-language-setting"')
    expect(general).toContain(':label="t(\'settings.general.defaultTargetLanguage\')"')
    expect(general).toContain(':description="t(\'settings.general.defaultTargetLanguageDescription\')"')
    expect(general).toContain('data-testid="translation-display-settings"')
    expect(general).toContain('<SettingsItem label="默认网页翻译服务"')
    expect(general).toContain(":description=\"t('quickTranslation.defaultServiceDescription')\"")
    expect(general).not.toContain('description="全文、悬浮和划词翻译默认使用此服务。"')
    expect(general).not.toContain('全文、悬浮、划词和输入框翻译默认使用此服务')
    expect(general).toContain('<template #prefix><ServiceIcon :service="config.service" :label="defaultTextServiceLabel" size="small"')
    expect(general).toContain('aria-label="默认网页翻译服务"')
    expect(general).toContain('defaultTextServiceLabel')
    expect(general).toContain(":aria-label=\"t('popup.aiContext.settingsTitle')\"")
    const aiContextSwitch = general.match(/<el-switch\b[^>]*v-model="config.enableAIContext"[^>]*\/>/u)?.[0]
    expect(aiContextSwitch).toBeDefined()
    expect(aiContextSwitch).not.toContain(':disabled')
    expect(general).toContain('label="翻译模式"')
    expect(general).toContain('aria-label="译文样式"')
    expect(general).toContain('v-model="config.bilingualSentenceHighlightEnabled"')
    expect(general).toContain(":label=\"t('settings.general.bilingualSentenceHighlight')\"")
    expect(general).toContain(":description=\"t('settings.general.bilingualSentenceHighlightDescription')\"")
    expect(general).toContain(":aria-label=\"t('settings.general.bilingualSentenceHighlight')\"")
    expect(general).toContain('data-testid="bilingual-highlight-preview"')
    expect(general).toContain('data-testid="bilingual-highlight-preview-source"')
    expect(general).toContain('data-testid="bilingual-highlight-preview-translation"')
    expect(general).toContain(':data-bilingual-highlight-enabled="String(config.bilingualSentenceHighlightEnabled)"')
    expect(general).toContain("'is-bilingual-highlight-enabled': config.bilingualSentenceHighlightEnabled")
    expect(styles).toContain('.bilingual-highlight-preview .is-sentence-highlighted')
    expect(styles).toContain('.bilingual-highlight-preview span:focus-visible')
    expect(general).toContain('@pointerenter="highlightPreviewSentence = index"')

    expect(services).toContain('<ServiceCatalog')
    expect(services).not.toContain('data-testid="default-translation-service-card"')
    expect(services).not.toContain('aria-label="默认网页翻译服务"')
    expect(services).not.toContain('<SettingsGroup')
    expect(styles).toContain('.service-default-control')
    expect(styles).not.toContain('.service-default-status')
    expect(styles).not.toContain('.service-default-picker')
    expect(styles).not.toContain('box-shadow: inset 4px 0 0 var(--brand);')
  })

  it('shows the complete grouped directory with direct search and custom service creation', () => {
    const catalog = source('src/features/settings/ui/services/ServiceCatalog.vue')
    const item = source('src/features/settings/ui/services/ServiceCatalogItem.vue')
    expect(catalog).not.toContain('data-service-view=')
    expect(catalog).not.toContain('catalog-browse')
    expect(catalog).not.toContain('no-model-panel')
    expect(catalog).not.toContain('data-service-section="mine"')
    expect(catalog).not.toContain('catalog-set-default')
    expect(catalog).not.toContain('myServices')
    expect(catalog).toContain('data-testid="custom-service-add"')
    expect(catalog).not.toContain('service-add-dialog')
    expect(catalog).toContain('v-for="group in visibleDirectoryGroups"')
    expect(catalog).toContain('v-for="item in group.items"')
    expect(catalog).toContain('v-model="serviceQuery"')
    expect(catalog).toContain("id: 'custom'")
    expect(catalog).not.toContain('maximumCustomServices')
    expect(item).toContain(':data-service-value="item.value"')
    expect(item).not.toContain('library-favorite')
    expect(item).toContain('<ServiceIcon')
  })

  it('keeps translation interactions together in the requested order', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const translation = activeSectionSource(settings, 'settings-translation')
    const inputTranslation = source('src/features/settings/ui/InputTranslationSettings.vue')
    const paragraphCopySettings = source('src/features/settings/ui/ParagraphCopySettings.vue')

    expect(settingsGroupTitles(translation)).toEqual([
      '鼠标悬浮翻译',
      '划词翻译',
      '全文翻译',
    ])
    expect(translation).toContain('aria-label="鼠标悬浮快捷键"')
    expect(translation).toContain('label="划词翻译模式"')
    expect(translation).toContain('<InputTranslationSettings')
    expect(inputTranslation.indexOf('data-testid="input-translation-trigger"')).toBeLessThan(inputTranslation.indexOf('data-testid="input-translation-target"'))
    expect(inputTranslation.indexOf('data-testid="input-translation-target"')).toBeLessThan(inputTranslation.indexOf('data-testid="input-translation-service"'))
    expect(inputTranslation).not.toContain('<el-dialog')
    expect(inputTranslation).toContain('class="input-translation-service-control"')
    expect(inputTranslation).toContain('<ServiceIcon')
    expect(translation).toContain('label="全文翻译范围"')
    expect(translation).toContain('aria-label="AI 多段翻译"')
    expect(translation).toContain('v-model="config.enableAIMultiSegment"')
    expect(translation.match(/<QuickTranslationProfiles\b/gu)).toHaveLength(2)
    expect(translation).toContain('action="hover"')
    expect(translation).toContain('action="full-page"')
    expect(translation.match(/:profiles="config\.quickTranslationProfiles"/gu)).toHaveLength(2)
    expect(translation.match(/@update:profiles="config\.quickTranslationProfiles = \$event"/gu)).toHaveLength(2)

    // 悬浮球详细设置属于全文翻译入口，段落复制紧随其后，形成翻译设置的末尾操作区。
    expect(translation).toContain('<ParagraphCopySettings :config="config" />')
    expect(translation).toContain('<FloatingBallSettings :config="config" />')
    expect(translation).toContain('id="floating-ball-settings"')
    expect(settingsGroupTitles(paragraphCopySettings)).toEqual(["t('paragraphCopy.settings.title')"])
    expect(paragraphCopySettings).toContain('data-testid="paragraph-copy-hotkey"')
    expect(paragraphCopySettings).toContain('data-testid="paragraph-copy-content"')
    expect(translation.indexOf('<FloatingBallSettings'))
      .toBeGreaterThan(translation.indexOf('title="全文翻译"'))
    expect(translation.indexOf('<ParagraphCopySettings'))
      .toBeGreaterThan(translation.indexOf('<FloatingBallSettings'))

    const hoverProfiles = translation.indexOf('action="hover"')
    const fullPageProfiles = translation.indexOf('action="full-page"')
    const inputTranslationSection = translation.indexOf('<InputTranslationSettings')
    expect(hoverProfiles).toBeGreaterThan(translation.indexOf('aria-label="悬浮翻译延迟"'))
    expect(hoverProfiles).toBeLessThan(translation.indexOf('title="划词翻译"'))
    expect(inputTranslationSection).toBeGreaterThan(translation.indexOf('title="划词翻译"'))
    expect(inputTranslationSection).toBeLessThan(translation.indexOf('title="全文翻译"'))
    expect(fullPageProfiles).toBeGreaterThan(translation.indexOf('label="全文翻译范围"'))
    expect(fullPageProfiles).toBeGreaterThan(translation.indexOf('aria-label="右键全文翻译"'))
  })

  it('loads shared tokens before the unchanged settings page rules', () => {
    const pageStyles = sourceBody('src/features/settings/ui/settings-page.css')
    const tokens = source('src/ui/styles/tokens.css')

    expect(pageStyles.startsWith('@import "../../../ui/styles/tokens.css";')).toBe(true)
    expect(tokens).toContain('--fr-color-brand: #ef4776;')
    expect(tokens).toContain('--surface-soft: var(--fr-color-surface-soft);')
  })

  it('keeps the desktop navigation scroll boundary stable while hovering its final item', () => {
    const pageStyles = sourceBody('src/features/settings/ui/settings-page.css')

    expect(pageStyles).toMatch(/nav\s*\{[^}]*min-height:\s*0;/u)
    expect(pageStyles).toMatch(/nav\s*\{[^}]*overflow-anchor:\s*none;/u)
    expect(pageStyles).toMatch(/@media \(min-width:\s*701px\)[\s\S]*?\.settings-app \.sidebar nav\s*\{[^}]*scrollbar-gutter:\s*stable;/u)
  })

  it('keeps bilingual sentence highlighting opt-in and scoped to bilingual wrappers', () => {
    const page = source('src/app/content/page.css')

    expect(page).toContain('::highlight(fluentread-bilingual-sentence)')
    expect(page).not.toContain(':hover > .fluent-read-bilingual-content::before')
    expect(page).not.toContain(':has(> .fluent-read-bilingual-content[data-fr-translation-owned="true"]):hover')
  })
})
